_target_: src.models.cifar10_module.CIFAR10LitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

net:
  _target_: timm.create_model
  model_name: resnet18
  pretrained: True
  num_classes: 10
  # _target_: src.models.components.simple_dense_net.SimpleDenseNet
  # lin1_size: 256
  # lin2_size: 256
  # lin3_size: 256
  # output_size: 10